### ISSUE TITLE
Rotina de cálculo de consumo quando hidrômetro é trocado

### ISSUE THREAD

**Issue by nexusbr** [prodigasistemas/gsan#214]
Gostaria que verificassem na rotina que calcula o consumo de um determinado usuário, se a mesma não realiza o cálculo pela média quando um hidrometro é trocado.
O que notamos que pode acontecer:
1. A companhia de saneamento decide trocar um grande número de hidrômetros antigos.
2. Com a troca o usuário que tinha o consumo mínimo devido ao hidrômetro anterior ser muito velho e não estar medindo, passa com o hidrômetro novo a ter um consumo bem maior do que o normal.
3. O GSAN percebe isso e faz o cálculo pela média (de quando o hidrômetro antigo não media mais) e a companhia de saneamento pode vir a ter uma perda de receita por este motivo, sendo difícil depois de detectada a não conformidade de cobrar o usuário devido a uma falha de indicação do consumo pelo GSAN.
Favor verificar se isto está ocorrendo na versão atual.

**Comment by nexusbr** [comment]
bom dia! Pinheiro
para te explicar a substituição de hidrometro
1o. o consumo em geral é calculado de forma projetada pelos dias de consumo medido no novo hidrometro
por exemplo: houve 17 dias de medição, calculado entre e data de instalação e a leitura do hidrômetro.
o sistema divide o consumo medido por 17 e multiplica pela quantidade de dias da rota
assim projeta a consumo estimado do mês para a cobrança
em apenas um caso é utilizado o consumo médio do imóvel
quanto a quantidade de dias medidos é inferior a 9 dias, porque pode causar distorções de consumo.
assim o GSAN utiliza e consumo médio, e na próxima leitura ajusta a cobrança conforme a leitura do hidrometro.
com por exemplo:
o consumo médio do imóvel era 10m3
o GSAN efetua a cobrança de 10m3, lança em leitura faturada o acréscimo dos 10m3
e na próxima leitura calcula o consumo pela diferença entre a leitura efetuada e a leitura faturada
assim o que por ventura tenha sido cobrando a maior ou a menor é compensado no mês
ok?
Joelma

**Comment by nexusbr** [comment]
A questão que pergunto é, por exemplo. O consumidor está pagando 10m3 por mês, devido a seu hidrômetro não estar medindo ou não ter hidrômetro, por exemplo.
Ai colocam um hidrômetro novo. E este no primeiro mês mede 40m3. Por que, pois ele estava gastando muita água devido a não estar medindo mesmo. O próprio consumidor não via isso.
Ai então na parametrização do GSAN ele pode entender que houve divergência e calcula pela média ao invés de enviar o consumo real do hidrômetro. 
O que acredito que acontece é uma questão de processo também, uma vez que este consumidor deveria ser avisado antes da troca do hidrômetro e que depois da troca, uns 10 dias depois com o hidrômetro novo, alguém da companhia de saneamento deveria ir lá e calcular na frente do consumidor quanto ele consumiu em 10 dias e assim alertá-lo que se ele continuasse assim a sua conta seria muito alta. 
De qualquer forma o que deve ser cobrado é o medido e não o pela média. 
Minha questão é: Isso realmente ocorre no GSAN?

**Comment by joelma-goncalves** [comment]
Pinheiro,

Esse caso ocorre da seguinte forma.
A média de consumo anterior do imóvel é 10m3
Ao efetuar a leitura pelo novo hidrômetro, projetada ou não, chega-se ao
consumo mensal de 40m3.

O sistema identifica uma anormalidade de consumo, e conforme configuração do
sistema, podemos ter 2 situações:

a) Enviar a conta para analise, onde os analistas de faturamento decidem com
emitir a fatura se pela condição cadastrada para a anormalidade (Média,
Mínimo da Categoria etc.) ou se fatura efetivamente o consumo medido.

Ou

b) O sistema registra a anormalidade de consumo e emite a conta pela
condição cadastrada para a anormalidade (Média, Mínimo da Categoria etc.).
Para posterior analise das anormalidades pelo setor competente e correção
das informações onde for necessário.


Att,


Joelma Gonçalves


From:  José Maria Villac Pinheiro <notifications@github.com>
Reply-To:  prodigasistemas/gsan
<reply+0053a2abf17f309212bd0dea993be9896a061de73ae4373b92cf000000011118103e9
2a169ce039d7063@reply.github.com>
Date:  quarta-feira, 11 de março de 2015 11:16
To:  prodigasistemas/gsan <gsan@noreply.github.com>
Subject:  Re: [gsan] Rotina de cálculo de consumo quando hidrômetro é
trocado (#214)


A questão que pergunto é, por exemplo. O consumidor está pagando 10m3 por
mês, devido a seu hidrômetro não estar medindo ou não ter hidrômetro, por
exemplo.
Ai colocam um hidrômetro novo. E este no primeiro mês mede 40m3. Por que,
pois ele estava gastando muita água devido a não estar medindo mesmo. O
próprio consumidor não via isso.
Ai então na parametrização do GSAN ele pode entender que houve divergência e
calcula pela média ao invés de enviar o consumo real do hidrômetro.
O que acredito que acontece é uma questão de processo também, uma vez que
este consumidor deveria ser avisado antes da troca do hidrômetro e que
depois da troca, uns 10 dias depois com o hidrômetro novo, alguém da
companhia de saneamento deveria ir lá e calcular na frente do consumidor
quanto ele consumiu em 10 dias e assim alertá-lo que se ele continuasse
assim a sua conta seria muito alta.
De qualquer forma o que deve ser cobrado é o medido e não o pela média.
Minha questão é: Isso realmente ocorre no GSAN?

‹
Reply to this email directly or view it on GitHub
<https://github.com/prodigasistemas/gsan/issues/214#issuecomment-78270888> .

**Comment by nexusbr** [comment]
Ok, entendi. Então é realmente uma questão de procedimento. As contas tem que ser enviadas para análise.
